spring:
#  data:
#    web:
#      pageable:
#        default-page-size: 12
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/webshopproject
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
token:
  time-to-live: 120
